name: PHP Code Sniffer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHP Code Sniffer
      run: composer phpcs
